Update to build and run on jdk9
ThoughtWorksInc/sbt-api-mappings pull request #11
Opened 2017-10-23 14:39 UTC by raboof

I also added a check to skip the boot classpath when it is not available. This might have to do with http://openjdk.java.net/jeps/261 .

2017-10-23 15:15 UTC, Atry requested changes
A Pull Request should focus on only one feature. Other changes, like upgrading sbt version for this project itself, should not be included in this PR.

2017-10-23 15:15 UTC, Atry commented on project/plugins.sbt
> -addSbtPlugin("com.thoughtworks.sbt-best-practice" % "sbt-best-practice" % "2.5.0")
The `sbt-best-practice` plugin is necessary for deployment.

2017-10-23 16:40 UTC, raboof commented
@Atry Fair enough - I've reverted the changes related to sbt1 and kept this PR focused on JDK9.

Unfortunately it appears the jdk9 build with sbt 0.13 fails on travis (while it succeeds for me locally), not sure what's going on there.

2017-10-23 16:46 UTC, Atry commented
@raboof It seems that we need Scala 2.10.7 for JDK9
https://github.com/scala/scala/pull/6128

2017-10-23 16:57 UTC, SethTisue commented
> It seems that we need Scala 2.10.7 for JDK9

and sbt 0.13.17

2017-10-23 17:14 UTC, raboof commented
@SethTisue ah - which isn't released yet - good to know!

Do I understand correctly that cross-building for 0.13.16 using the 1.0.2 launcher does work on jdk9, but building for sbt 0.13 'directly' doesn't until 0.13.17 is out? Or do we need 0.13.7 in both cases?

2017-11-15 04:30 UTC, Atry commented
`sbt-api-mappings` should be able to run on JDK9 if we merge this PR and publish a new binary release, despite of the tests on JDK9 is not able to run until sbt 0.13.17 because this plugin itself use 0.13.x.

2017-12-08 08:08 UTC, closed without merging